# https://taskfile.dev

version: "3"

vars:
  VPNX_OUTPUT: bin/vpnx

tasks:
  build-vpnx:
    cmds:
      - go build -o "{{.VPNX_OUTPUT}}" ./cmd/vpnx

  build-all:
    cmds:
      - task build-vpnx build-vpnxd

  test:
    cmds:
      - go test ./...
