package gluetun

import z "github.com/Oudwins/zog"

type gluetunVersion []gluetunEnv

func (g gluetunVersion) envMap() map[string]gluetunEnv {
	result := make(map[string]gluetunEnv, len(g))
	for _, env := range g {
		result[env.name()] = env
	}
	return result
}

var onOffValues = []string{"on", "off"}

var vpnProviderValues = []string{
	"airvpn",
	"Custom",
	"cyberghost",
	"expressvpn",
	"fastestvpn",
	"giganews",
	"hidemyass",
	"ipvanish",
	"ivpn",
	"mullvad",
	"nordvpn",
	"perfect-privacy",
	"privado",
	"private-internet-access",
	"privatevpn",
	"protonvpn",
	"purevpn",
	"slickvpn",
	"surfshark",
	"torguard",
	"vpn-secure",
	"vpn-unlimited",
	"vyprvpn",
	"windscribe",
}

var dnsUpstreamResolverValues = []string{
	"circa family",
	"circa private",
	"circa protected",
	"cleanbrowsing",
	"adult",
	"cleanbrowsing family",
	"cleanbrowsing security",
	"cloudflare",
	"cloudflare family",
	"cloudflare security",
	"google",
	"libredns",
	"opendns",
	"quad9",
	"quad9 secured",
	"quad9 unsecured",
	"quadrant",
}

var publicIPAPIValues = []string{
	"ipinfo",
	"ifconfigco",
	"ip2location",
	"cloudflare",
}

var gluetunVersion3 = gluetunVersion{
	newGluetunEnv("HTTP_CONTROL_SERVER_ADDRESS", z.String().TestFunc(isValidListeningAddress)),
	newGluetunEnv("HTTP_CONTROL_SERVER_LOG", stringEnumSchema(onOffValues)),
	newGluetunEnv("HTTP_CONTROL_SERVER_AUTH_CONFIG_FILEPATH", z.String().TestFunc(isValidFilePath)),
	newGluetunEnv("DNS_UPSTREAM_RESOLVER_TYPE", stringEnumSchema([]string{"dot", "doh", "plain"})),
	newCSVGluetunEnv[string]("DNS_UPSTREAM_RESOLVER", z.Slice(stringEnumSchema(dnsUpstreamResolverValues).Required())),
	newGluetunEnv("DNS_CACHING", stringEnumSchema(onOffValues)),
	newGluetunEnv("DNS_UPSTREAM_IPV6", stringEnumSchema(onOffValues)),
	newCSVGluetunEnv[string]("DNS_BLOCK_IPS", z.Slice(z.String().IP())),
	newCSVGluetunEnv[string]("DNS_BLOCK_IP_PREFIXES", z.Slice(z.String())),
	newCSVGluetunEnv[string]("DNS_REBINDING_PROTECTION_EXEMPT_HOSTNAMES", z.Slice(z.String().TestFunc(isValidHostname))),
	newGluetunEnv("DNS_UPDATE_PERIOD", z.String().TestFunc(isValidTimePeriod)),
	newGluetunEnv("BLOCK_MALICIOUS", stringEnumSchema(onOffValues)),
	newGluetunEnv("BLOCK_SURVEILLANCE", stringEnumSchema(onOffValues)),
	newGluetunEnv("BLOCK_ADS", stringEnumSchema(onOffValues)),
	newCSVGluetunEnv[string]("DNS_UNBLOCK_HOSTNAMES", z.Slice(z.String().TestFunc(isValidHostname))),
	newCSVGluetunEnv[string]("DNS_UPSTREAM_PLAIN_ADDRESSES", z.Slice(z.String().TestFunc(isValidPlainAddress))),
	newCSVGluetunEnv[int]("FIREWALL_VPN_INPUT_PORTS", z.Slice(z.Int().GTE(0).LTE(65535))),
	newCSVGluetunEnv[int]("FIREWALL_INPUT_PORTS", z.Slice(z.Int().GTE(0).LTE(65535))),
	newGluetunEnv("FIREWALL_DEBUG", stringEnumSchema(onOffValues)),
	newCSVGluetunEnv[string]("FIREWALL_OUTBOUND_SUBNETS", z.Slice(z.String().TestFunc(isValidSubnet))),
	newCSVGluetunEnv[string]("HEALTHCHECK_TARGET_ADDRESSES", z.Slice(z.String())),
	newCSVGluetunEnv[string]("HEALTHCHECK_ICMP_TARGET_IPS", z.Slice(z.String().IPv4())),
	newGluetunEnv("HEALTHCHECK_SERVER_ADDRESS", z.String().TestFunc(isValidPlainAddress)),
	newGluetunEnv("HEALTHCHECK_RESTART_VPN", stringEnumSchema(onOffValues)),
	newGluetunEnv("HTTPPROXY_STATUS", stringEnumSchema(onOffValues)),
	newGluetunEnv("HTTPPROXY_LOG", stringEnumSchema(onOffValues)),
	newGluetunEnv("HTTPPROXY_LISTENING_ADDRESS", z.String().TestFunc(isValidListeningAddress)),
	newGluetunEnv("HTTPPROXY_USER", z.String()),
	newGluetunEnv("HTTPPROXY_PASSWORD", z.String()),
	newGluetunEnv("HTTPPROXY_STEALTH", stringEnumSchema(onOffValues)),
	newGluetunEnv("OPENVPN_USER", z.String().Required()),
	newGluetunEnv("OPENVPN_PASSWORD", z.String().Required()),
	newGluetunEnv("OPENVPN_PROTOCOL", stringEnumSchema([]string{"tcp", "udp"})),
	newNumberGluetunEnv("OPENVPN_VERSION", floatEnumSchema([]float64{2.5, 2.6})),
	newGluetunEnv("OPENVPN_ENDPOINT_IP", z.String().IP()),
	newNumberGluetunEnv("OPENVPN_ENDPOINT_PORT", z.Int().GTE(0).LTE(65535)),
	newNumberGluetunEnv("OPENVPN_VERBOSITY", intEnumSchema([]int{0, 1, 2, 3, 4, 5, 6})),
	newCSVGluetunEnv[string]("OPENVPN_FLAGS", z.Slice(z.String())),
	newGluetunEnv("OPENVPN_ROOT", stringEnumSchema(onOffValues)),
	newGluetunEnv("OPENVPN_CIPHERS", z.String()),
	newGluetunEnv("OPENVPN_AUTH", z.String()),
	newNumberGluetunEnv("OPENVPN_MSSFIX", z.Int().GTE(0).LTE(9999)),
	newGluetunEnv("OPENVPN_CERT", z.String().TestFunc(isValidBase64PEM)),
	newGluetunEnv("OPENVPN_KEY", z.String().TestFunc(isValidBase64PEM)),
	newGluetunEnv("OPENVPN_ENCRYPTED_KEY", z.String().TestFunc(isValidBase64PEM)),
	newGluetunEnv("OPENVPN_KEY_PASSPHRASE", z.String()),
	newGluetunEnv("OPENVPN_PROCESS_USER", z.String()),
	newGluetunEnv("OPENVPN_CUSTOM_CONFIG", z.String().TestFunc(isValidFilePath)),
	newGluetunEnv("LOG_LEVEL", stringEnumSchema([]string{"debug", "info", "warn", "error"})),
	newGluetunEnv("TZ", z.String()),
	newNumberGluetunEnv("PUID", z.Int()),
	newNumberGluetunEnv("PGID", z.Int()),
	newBoolGluetunEnv("PUBLIC_IP_ENABLED", z.Bool()),
	newCSVGluetunEnv[string]("PUBLIC_IP_API", z.Slice(stringEnumSchema(publicIPAPIValues).Required())),
	newGluetunEnv("PUBLIC_IP_API_TOKEN", z.String()),
	newGluetunEnv("PUBLIC_IP_FILE", z.String().TestFunc(isValidFilePath)),
	newGluetunEnv("VERSION_INFORMATION", stringEnumSchema(onOffValues)),
	newGluetunEnv("BORING_POLL_GLUETUN_COM", stringEnumSchema(onOffValues)),
	newGluetunEnv("VPN_PORT_FORWARDING", stringEnumSchema(onOffValues)),
	newGluetunEnv("VPN_PORT_FORWARDING_PROVIDER", stringEnumSchema([]string{
		"private",
		"internet access",
		"perfect privacy",
		"privatevpn",
		"protonvpn",
	})),
	newGluetunEnv("VPN_PORT_FORWARDING_STATUS_FILE", z.String().TestFunc(isValidFilePath)),
	newNumberGluetunEnv("VPN_PORT_FORWARDING_LISTENING_PORT", z.Int().GTE(0).LTE(65535)),
	newGluetunEnv("VPN_PORT_FORWARDING_UP_COMMAND", z.String()),
	newGluetunEnv("VPN_PORT_FORWARDING_DOWN_COMMAND", z.String()),
	newGluetunEnv("SHADOWSOCKS", stringEnumSchema(onOffValues)),
	newGluetunEnv("SHADOWSOCKS_LOG", stringEnumSchema(onOffValues)),
	newGluetunEnv("SHADOWSOCKS_LISTENING_ADDRESS", z.String().TestFunc(isValidListeningAddress)),
	newGluetunEnv("SHADOWSOCKS_PASSWORD", z.String()),
	newGluetunEnv("SHADOWSOCKS_CIPHER", stringEnumSchema([]string{
		"chacha20-ietf-poly1305",
		"aes-128-gcm",
		"aes-256-gcm",
	})),
	newGluetunEnv("STORAGE_FILE_PATH", z.String().TestFunc(isValidFilePath)),
	newGluetunEnv("UPDATER_PERIOD", z.String().TestFunc(isValidTimePeriod)),
	newNumberGluetunEnv("UPDATER_MIN_RATIO", z.Float64().GT(0).LTE(1)),
	newCSVGluetunEnv[string]("UPDATER_VPN_SERVICE_PROVIDERS", z.Slice(stringEnumSchema(vpnProviderValues).Required())),
	newGluetunEnv("PROTONVPN_EMAIL", z.String().Email()),
	newGluetunEnv("PROTONVPN_PASSWORD", z.String()),
	newGluetunEnv("VPN_SERVICE_PROVIDER", stringEnumSchema(vpnProviderValues)),
	newGluetunEnv("VPN_TYPE", stringEnumSchema([]string{"wireguard", "openvpn"})),
	newGluetunEnv("VPN_INTERFACE", z.String()),
	newGluetunEnv("VPN_UP_COMMAND", z.String()),
	newGluetunEnv("VPN_DOWN_COMMAND", z.String()),
	newGluetunEnv("WIREGUARD_PRIVATE_KEY", z.String().Required()),
	newCSVGluetunEnv[string]("WIREGUARD_ADDRESSES", z.Slice(z.String().TestFunc(isValidSubnet)).Required()),
	newGluetunEnv("WIREGUARD_PUBLIC_KEY", z.String().Required()),
	newGluetunEnv("WIREGUARD_ENDPOINT_IP", z.String().Required().IP()),
	newNumberGluetunEnv("WIREGUARD_ENDPOINT_PORT", z.Int().Required().GTE(0).LTE(65535)),
	newGluetunEnv("WIREGUARD_PRESHARED_KEY", z.String()),
	newCSVGluetunEnv[string]("WIREGUARD_ALLOWED_IPS", z.Slice(z.String())),
	newGluetunEnv("WIREGUARD_IMPLEMENTATION", stringEnumSchema([]string{"auto", "kernelspace", "userspace"})),
	newNumberGluetunEnv("WIREGUARD_MTU", z.Int().GTE(0).LTE(1440)),
	newGluetunEnv("WIREGUARD_PERSISTENT_KEEPALIVE_INTERVAL", z.String().TestFunc(isValidTimePeriod)),
}
