package config

const (
	APP_NAME               = "VPNx"
	GLUETUN_TARGET_VERSION = "3.40.2"
	DEFAULT_CONFIG_VERSION = CONFIG_VERSION_ONE
	DEFAULT_LOG_LEVEL      = LOG_LEVEL_INFO
	DEFAULT_VPN_TYPE       = VPN_TYPE_WIREGUARD

	XDG_CONFIG_HOME = "XDG_CONFIG_HOME"
	XDG_DATA_HOME   = "XDG_DATA_HOME"
	XDG_STATE_HOME  = "XDG_STATE_HOME"
	XDG_CACHE_HOME  = "XDG_CACHE_HOME"

	XDG_HOME   = "HOME"
	XDG_CONFIG = "/.config"
	XDG_DATA   = "/.local/share"
	XDG_STATE  = "/.local/state"
	XDG_CACHE  = "/.cache"
)
